version: "3.9"
name: "overprotocol"

networks:
  over-dolphin-network:
    name: over-dolphin-network
    external: true

services:
  validator-dolphin:
    restart: unless-stopped
    image: overfoundation/chronos-validator:latest
    container_name: validator-dolphin
    networks:
      - over-dolphin-network
    volumes:
      - ./wallet:/wallet
      - ./datadir/validator:/data
    command: >
      --wallet-dir /wallet
      --datadir /data
      --beacon-rpc-provider http://chronos:4000
      # --suggested-fee-recipient

